// File generated by Antigravity AI.
// This is a placeholder template to ensure the project compiles cleanly.
// It will be overwritten automatically when you run 'flutterfire configure'.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTS6MMdfz8NckUXl83YIv8-XdNQBBMCI',
    appId: '1:369024297315:android:08829ed5e2e68e40248b56',
    messagingSenderId: '369024297315',
    projectId: 'chopnow-75716',
    storageBucket: 'chopnow-75716.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2O7mTC2gR-6kiTyhPxEgOZ7RvPrQdzmk',
    appId: '1:369024297315:ios:6dd48dcf3cf6e5f2248b56',
    messagingSenderId: '369024297315',
    projectId: 'chopnow-75716',
    storageBucket: 'chopnow-75716.firebasestorage.app',
    iosClientId: '369024297315-vbs41mq0fj07ej14oqm39u6lr7p12f1p.apps.googleusercontent.com',
    iosBundleId: 'com.chopnow.chopnow',
  );
}
